export const data = [
    { id:32, color:"red",  option: '32'  },
    { id:15, color:"black", option: '15'  } ,
    { id:19, color:"red", option: '19' },
    { id:4, color:"black", option: '4' },
    { id:21, color:"red", option: '21'},
    { id:2, color:"black", option: '2' },
    { id:25, color:"red", option: '25' },
    { id:17, color:"black", option: '17' },
    { id:34, color:"red", option: '34' },
    { id:6, color:"black", option: '6' },
    { id:27, color:"red", option: '27'},
    { id:13, color:"black", option: '13' },
    { id:36, color:"red", option: '36'},
    { id:11, color:"black", option: '11' },
    { id:30, color:"red", option: '30' },
    { id:8, color:"black", option: '8' },
    { id:23, color:"red", option: '23' },
    { id:10, color:"black", option: '10' },
    { id:5, color:"red", option: '5' },
    { id:24, color:"black", option: '24' },
    { id:16, color:"red", option: '16' },
    { id:33, color:"black", option: '33' },
    { id:1, color:"red", option: '1' },
    { id:20, color:"black", option: '20' },
    { id:14, color:"red", option: '14' },
    { id:31, color:"black", option: '31' },
    { id:9, color:"red", option: '9' },
    { id:22, color:"black", option: '22' },
    { id:18, color:"red", option: '18' },
    { id:29, color:"black", option: '29' },
    { id:7, color:"red", option: '7' },
    { id:28, color:"black", option: '28' },
    { id:12, color:"red", option: '12'},
    { id:35, color:"black", option: '35' },
    { id:3, color:"red", option: '3' },
    { id:26, color:"black", option: '26' },
    { id:0, option: '0', style: { backgroundColor: 'green'  } },
  ]


// export const data = [
//   { id:1, color:"red",  option: "1" },
//   { id:2, color:"black", option: "2"  },
// ]